# Generated by Django 4.0.1 on 2022-02-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='especialidad_medico',
            unique_together={('id_medico', 'id_especialidad', 'dia_laboral', 'horario')},
        ),
    ]
