# Generated by Django 4.0.1 on 2022-02-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_especialidad_medico_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.TextField(verbose_name='Diagnóstico'),
        ),
    ]
